language: ruby
rvm:
  - 2.1.1
  - 1.9.3
before_script:
  - psql -c 'create database soso_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
# script: bundle exec rspec -f progress spec
