# Use 'createuser -s postgres' to create a general purpose db (super)user.

development: &default
  adapter: postgresql
  database: soso3_development
  username: iaeste_soso
  password: "234"
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: soso3_test
  min_messages: warning
