# Use 'createuser -s postgres' to create a general purpose db (super)user.

default: &default
  adapter: postgresql
  username: soso3
  password: soso3

development:
  <<: *default
  database: soso3_dev
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: soso3_test
  min_messages: warning

production:
  <<: *default
  database: iaeste_soso
  username: iaeste_soso
  password: 'secret'

heroku:
  <<: *default
  database: dfpobsebvk8sol
  username: sqcqkytiueognd
